- admin_dashboard.html
- styles.css
> Fixed dark mode striping

- admin_dashboard.html
- index.html
- styles.css
Fixed some table sizing and button issues. Added colors to statuses
> Fixed some table sizing and button issues. Added colors to statuses

- admin_announcement.html
- admin_dashboard.html
- applicationform.html
- contactForm.html
- index.html
- phptest.html
- signup.html
- styles.css
Fixed dark mode slider, mobile tables, nav added admin announcement on all pages, removed user table on index page
> Fixed dark mode slider, mobile tables, nav added admin announcement on all pages, removed user table on index page

- admin_announcement.html
- admin_dashboard.html
- applicationform.html
- contactForm.html
- index.html
- js/applicationscript.js
- js/contactscript.js
- js/main.js
- js/signupscript.js
- signup.html
- signupPHP.php
- styles.css
New Footer added with links. Buttons now using :hover css
> New Footer added with links. Buttons now using :hover css

- admin_dashboard.html
- index.html
- js/main.js
Removed conflicting button classes and commented out dark mode logs for now
> Removed conflicting button classes

- admin_dashboard.html
- index.html
- styles.css
Added update account style to btn
> Added update account style to btn

- adminannouncementPHP.php
- applicationformPHP.php
- contactPHP.php
Updated header and footer for php pages. Fixed admin announcement php fail if more info is empty
> Updated header and footer for php pages. Fixed admin announcement php fail if more info is empty

- admin_announcement.html
- applicationform.html
- applicationformPHP.php
Added a quick fix for empty non-required fields failing a php form. changed php forms to not be the dragonfly ones
> Added a quick fix for empty non-required fields failing a php form. changed php forms to not be the dragonfly ones

- adminannouncementPHP.php
- signupPHP.php
link on adminannouncementphp went to wrong direction. Fixed signupphp to be formatted like the other php pages (allow dark mode and look nicer overall)
> Small formatting fixes

- admin_announcement.php
- admin_dashboard.php
- application_form.php
- contact_form.php
- footer.php
- header.php
- index.html
- index.php
- js/dashboard.js
- js/main.js
- page_template.php
- signup_form.php
- styles.css
Created admin_announcement.php, admin_dashboard.php, application_form.php, index.php, signup_form.php, and page_template.php. index.php uses header.php and footer.php. Renamed contactForm.php to contact_form.php
Removed js functions for old footer
> Created new php files for each page

- application_form.php
- contact_form.php
- signup_form.php
Javascript was missing on app and signup form. Added small comment on contact form to make it cohesive with the rest. Added a maxlength to everything the user can submit into the database to match the varchar amount in database.
> Database frontend validation & Javascript inclusion. 

- admin_announcement.php
- admin_dashboard.php
- application_form.php
- contact_form.php
- index.php
- php/admin_announcement_submit.php
- php/application_submit.php
- php/contact_submit.php
- php/footer.php
- php/nav_bar.php
- php/page_template.php
- php/signup_submit.php
- signup_form.php
Added relativity to every page. Fixed dropdown validation on application_form.php. (You cant pick select and small text appears if you try to submit with select, selected)
> Added relativity. Some fixes on specific pages

- index.php
- js/dashboard.js
- styles/styles.css
Fixed the status colors that weren't getting the correct css class added. Added the new functions in dashboard.js to delete app elements from user dashboard
> Fixed some CSS styles. Added new delete app functions in dashboard.js.

- php/admin_announcement_submit.php
Added functionality to insert announcements to database on submit
> Added functionality to insert announcements to database on submit

- php/admin_announcement_submit.php
Fixed some layout problems with admin_announcement_submit.php
> Fixed some layout problems with admin_announcement_submit.php

- application_edit.php
- index.php
- php/application_update.php
Changed button in index to make form so it can submit to another page. Might want to make this a modal a future, this is just a solution that works right now. Added application_edit.php and application_update.php. edit is the page that looks very similar to application_form but it auto inputs the values from the id gotten from index page. update is a page that looks very similar to application_submit but the sql is update instead of insert.
> Added edit application functionality

- index.php
- js/dashboard.js
- php/admin_announcement_submit.php
- php/application_submit.php
- php/application_update.php
- php/signup_submit.php
- styles/styles.css
Added search functionality to user dashboard and fixed some php database location errors
> Added search functionality to user dashboard

- index.php
- js/dashboard.js
- php/admin_announcement_submit.php
- php/application_submit.php
- php/contact_submit.php
- php/signup_submit.php
App list no longer shows apps that were deleted. Still needs functionality to delete
> Couple php location fixes and some app list error fixes

- index.php
- js/dashboard.js
Added the functionality to delete from app list on user dashboard
> Added the functionality to delete from app list on user dashboard

- js/dashboard.js
Fixed app sort to ignore capitalization
> Fixed app sort to ignore capitalization

- index.php
- js/dashboard.js
Replaced application creation function with an easier to read function and only a single append call
> Replaced application creation function with an easier to read function and only a single append call

- admin_dashboard.php
- js/dashboard.js
- styles/styles.css
Fixed Need-To-Apply by removing dashes and changing the color back to brown. Added the modal, looks very similar to Yadira's admin dashboard reminder modals. One little error with the links in the modals where they can not work if https:// is added. I'll fix that in the future.
> Added View Application Modal on Index page

- js/dashboard.js
Allowed job urls to be clickable no matter what they put in
> Changed edit app modal

- js/dashboard.js
Centered and made the title text a bit larger
> Small format changes on view application modal

- index.php
Added php to fill in the application follow up announcements from the DB into the user dashboard announcement area. Added date filtering for the SQL commands.
> Added to Announcement in User dashboard

- admin_dashboard.php
- index.php
- js/dashboard.js
- php/application_update.php
Made apps Modals a single Modal on index.php and on admin_dashboard.php and filled this info in on click or on edit click. Admin dash doesnt show edit and delete btns now. Admin Also added a JOIN to the sql to attach user info to the application
> Updated modal view to a single modal and admin dash now searches

- admin_dashboard.php
- index.php
- js/dashboard.js
- styles/styles.css
Made user first, last, and email searchable on admin dash. Headers are easier to click now for sorting. Added Name and Email to app-modal
> Fixed some size issues with the dashboard widths. 

- admin_dashboard.php
Fixed sql statement for applications to filter out deleted apps and deleted users
> Fixed sql statement for applications to filter out deleted apps and deleted users

- admin_dashboard.php
- js/dashboard.js
- styles/styles.css
Added search functionality to user list. Can search by name, email, status, and now the admin can choose show deleted users or hide deleted users, in case access to a deleted user is needed by an admin.
> Added search functionality to user list. 

- index.php
- js/dashboard.js
It now makes sure the role is an admin before loading users (This can be set later with a login)
> Fixed an issue with user dashboard trying to load users. 

- admin_dashboard.php
- js/dashboard.js
- styles/styles.css
Refactored dashboard.js code and added more comments to make it more clean and understandable. app dash and user dash have matching sort buttons for each header field. Deleted users on admin dash are easier to spot
> Refactored dashboard.js code and added user sort by fields function

- admin_dashboard.php
- index.php
- js/dashboard.js
- php/application_submit.php
- styles/styles.css
Toast now works and slides down saying 'app was deleted' or 'user was deleted', then slides up and disappears after 2 seconds. Delete user modal and delete app modal have more info showing what you are deleting so there is less ambiguity
> Deleted toast app/user toast now works. Modals show name of user or app being deleting

- admin_dashboard.php
- index.php
- js/dashboard.js
- styles/styles.css
app reminders on user dash didnt work and there wasnt a way to edit them so they now can be viewed and edited from user dashboard. announcement table on admin dash is now displaying correctly with a long url
> app reminders on user dash didnt work and there wasnt a way to edit them so they now can be viewed and edited from user dashboard

- login.php
- logout.php
Built basic structure for login page and stubbed in the session_start.
> Added login and logout pages. 

- js/main.js
- js/themescript.js
- styles/styles.css
Added functionality to save DarkMode preference with cookies. The localstorage darkmode methods were left in and commented out so either can be used.
> Added functionality to save DarkMode preference with cookies.

- login.php
Login now checks the DB and validates password match, then assigns the user_id to a session variable that can be used on other pages. I also removed the Nav bar for the sign in page.
> Login checks DB for password

- admin_dashboard.php
- index.php
- js/dash-apps.js
- js/dash-functions.js
- js/dash-users.js
- login.php
- php/application_update.php
- php/nav_bar.php
- styles/styles.css
index now shows only apps for user signed in from login.php. Admin buttons on nav only show for people with admin permission. Admins cant click their own make admin button on user list. If someone is an admin already, make admin button shows "remove admin" (remove admin not functional yet). Added a small welcome, $name! message on navbar. Split dashboard.js into dash-functions, dash-apps, and dash-users
> added some functionality to check user id on sign in and only show appropriate pages

- admin_dashboard.php
- index.php
- js/dash-apps.js
- login.php
- php/nav_bar.php
- user_check.php
After login, user gets sent to index and admin is sent to admin dash. Navbar only shows user buttons and admin only shows admin buttons. added a user_check.php which can be added after session_start() and it will send a logged out user to the login.php page
> After login, user gets sent to index and admin is sent to admin dash.

- app_tracker_dump.sql
Added more users, more applications, more announcements. Added more fields to be up to date to our database. If you copy paste the whole file it works.
> SQL dump updated

- admin_announcement.php
- admin_dashboard.php
- application_edit.php
- application_form.php
- contact_form.php
- index.php
- js/navbar.js
- login.php
- logout.php
- php/nav_bar.php
- php/roles/admin_check.php
- php/roles/admin_kick.php
- php/roles/logout_check.php
- php/roles/user_check.php
- php/roles/user_kick.php
- signup_form.php
- styles/styles.css
Role checks added to non-submit php files. Dropdown menu added to navbar for logout and dark mode buttons.
> Role checks added to non-submit php files. Dropdown menu added to navbar for logout and dark mode buttons.

- php/admin_announcement_submit.php
- php/application_submit.php
- php/application_update.php
- php/contact_submit.php
- php/signup_submit.php
Application_submit now submits the user_id instead of hard-coding a user_id of 1. Added redirects for all form submits
> Application_submit now submits the user_id instead of hard-coding a user_id of 1. Added redirects for all form submits

- admin_dashboard.php
- js/dash-users.js
- php/roles/admin_check.php
Added functionality to remove admin status. Also added an extra check to ensure an admin is logged in right before doing any admin database queries
> Added functionality to remove admin status. Also added an extra check to ensure an admin is logged in right before doing any admin database queries

- index.php
- php/edit_account_update.php
- php/nav_bar.php
- user_edit.php
Button in nav bar looks a little sad, but it works
> Added editing users

- admin_dashboard.php
- js/dash-users.js
- styles/styles.css
Added modal, changed style a little bit on the button inside the modal, added ability to go to link
> Edit user added on admin dashboard

- admin_dashboard.php
- index.php
- js/dash-announcements.js
- js/dash-apps.js
- js/dash-functions.js
- js/dash-users.js
Also Fixed follow-ups so they open in the view-app modal on the user dash. Annnouncements still have an edit button that goes to a missing 'edit_announcement.php' file for now
> Fixed announcements so they open in a single modal.

- admin_dashboard.php
- index.php
- js/dash-announcements.js
- js/dash-apps.js
- js/dash-functions.js
- js/main.js
- js/navbar.js
- php/edit_account_update.php
- php/nav_bar.php
- styles/styles.css
- user_edit.php
Still doesn't work for the user announcements/followups yet and any dates in modals but this will be fixed.
> Added date format select in the navbar user dropdown. 

- admin_dashboard.php
- index.php
- js/dash-announcements.js
- js/dash-apps.js
- js/dash-users.js
- php/admin_announcement_submit.php
- php/application_submit.php
- php/application_update.php
- php/contact_submit.php
- php/edit_account_update.php
- php/signup_submit.php
- styles/styles.css
Basically everything is now created and shown the same way through javascript. Fixed some small things in the js functions and put the data sent over to javascript in a single JSON variable instead of a bunch of variables. Fixed some mobile views
> Fixed the date format for user announcements and followups. Fixed some mobile views

- admin_dashboard.php
- js/dash-announcements.js
- js/dash-apps.js
- js/dash-users.js
- styles/styles.css
Fixed a bug in the sort and search functions where the list order would reset when a new field was add or removed. All Lists now stay in the correct order no matter the search terms
> Added search functionality to announcements on admin dashboard and fixed a sort/search bug

- login.php
- php/signup_submit.php
Fixed if logic on the Cohort and Roles for signup_submit.php, added password hashing for signup_submit.php so passwords are stored encrypted in the DB, added password de-encryption to login.php
> Added Password encryption, fixed logic in signup_submit.php

- admin_dashboard.php
- js/dash-functions.js
- js/user-edit.js
- php/edit_account_update.php
- php/nav_bar.php
- php/signup_submit.php
- user_edit.php
added ability to choose whether to change your password or not on update user screen
> Fixed a bunch of user_edit errors

- admin_announcement.php
- login.php
- page_locations.php
- php/admin_announcement_submit.php
- php/nav_bar.php
- php/roles/timeout_check.php
- styles/styles.css
- timed_out.php
Added a timeout script to destroy the session if user is idle for more than 30 mins. Each time they visit a new page it resets. Also added timeout after session is 8 horus long no matter what. Fixed calendar picker icon color in dark mode.
> Added session timeout script and fixed date picker icon color

- admin_announcement.php
- admin_dashboard.php
- application_edit.php
- application_form.php
- contact_form.php
- header.php
- index.php
- js/dash-functions.js
- login.php
- php/admin_announcement_submit.php
- php/application_submit.php
- php/application_update.php
- php/contact_submit.php
- php/edit_account_update.php
- php/nav_bar.php
- php/roles/admin_check.php
- php/roles/admin_kick.php
- php/roles/logout_check.php
- php/roles/timeout_check.php
- php/roles/user_check.php
- php/roles/user_kick.php
- php/signup_submit.php
- signup_form.php
- timed_out.php
- user_edit.php
Added ob_start() to all files in order for redirects to work correctly on cpanel. Put a timeout_check on each page to log users out after 30 mins. Fixed the login check so it checks lowercase of email fields so the capital mismatch doesn't fail the login
> Added ob_start() to all files in order for redirects to work correctly on cpanel and other login fixes.

- admin_dashboard.php
- index.php
- js/dash-announcements.js
- js/dash-apps.js
- js/dash-functions.js
- js/dash-users.js
- php/edit_account_update.php
- php/empty_form_msg.php
- styles/styles.css
Navbar welcome message name now updates when user changes their name in the middle of the session. Added functionality to bring deleted user back
> Navbar welcome message name now updates when user changes their name in the middle of the session. Added functionality to bring deleted user back

- admin_dashboard.php
- index.php
- js/dash-announcements.js
- js/dash-apps.js
- php/admin_announcement_submit.php
Fixed an issue with there being errors when there are no app reminders for a user. Fixed an issue in admin_announcement_submit where the job location variable was sharing itself with the folder $location variable. job location is now $jobLocation
> Fixed an issue with there being errors when there are no app reminders for a user. Fixed an issue in admin_announcement_submit $location variable

- index.php
- user_edit.php
Removed the * from roles and changed follow up date from -15 days back to -5 days
> Removed the * from roles and changed follow up date from -15 days back to -5 days
